// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_app from './routes/_app.tsx'
import * as $_middleware from './routes/_middleware.ts'
import * as $index from './routes/index.tsx'
import * as $logout from './routes/logout.tsx'
import * as $members_albums_slug_ from './routes/members/albums/[slug].tsx'
import * as $members_albums_index from './routes/members/albums/index.tsx'
import * as $members_index from './routes/members/index.tsx'

import { type Manifest } from '$fresh/server.ts'

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/_middleware.ts': $_middleware,
    './routes/index.tsx': $index,
    './routes/logout.tsx': $logout,
    './routes/members/albums/[slug].tsx': $members_albums_slug_,
    './routes/members/albums/index.tsx': $members_albums_index,
    './routes/members/index.tsx': $members_index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
